#!/usr/bin/python3

"""
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.?
"""

def euler2() -> int:
    a = 1
    b = 2
    tot = 0
    while a < 4000000:
        if a%2 == 0:
            tot = tot + a
        c = a + b
        a = b
        b = c
    return tot

tot = euler2()
print(tot)
        
